In [40]:
# Keras based on both Tensorflow and Theano
!pip install Theano

**Part 1 - Data Preprocessing**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset[:5]

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.iloc[:, 3: -1].values   # Include those columns that might involve in affecting the result
y = dataset.iloc[:, -1].values

In [44]:
print("X: \n" + str(X[:5]))
print("y: \n" + str(y[:5]))

X: 
[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]]
y: 
[1 0 1 0 0]


In [0]:
# Encoding since there is not numerical values
# Like example France, Female, Spain...

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])   # For country
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])   # For gender

# OneHotEncoder for country
transformer = ColumnTransformer(
    transformers=[
        ("OneHot",        # Just a name
         OneHotEncoder(), # The transformer class
         [1]              # The column(s) to be applied on.
         )
    ],
    remainder='passthrough' # donot apply anything to the remaining columns
)
X = transformer.fit_transform(X.tolist())
X = X.astype('float64').tolist()

In [46]:
print("X: \n" + str(X[:5]))

X: 
[[1.0, 0.0, 0.0, 619.0, 0.0, 42.0, 2.0, 0.0, 1.0, 1.0, 1.0, 101348.88], [0.0, 0.0, 1.0, 608.0, 0.0, 41.0, 1.0, 83807.86, 1.0, 0.0, 1.0, 112542.58], [1.0, 0.0, 0.0, 502.0, 0.0, 42.0, 8.0, 159660.8, 3.0, 1.0, 0.0, 113931.57], [1.0, 0.0, 0.0, 699.0, 0.0, 39.0, 1.0, 0.0, 2.0, 0.0, 0.0, 93826.63], [0.0, 0.0, 1.0, 850.0, 0.0, 43.0, 2.0, 125510.82, 1.0, 1.0, 1.0, 79084.1]]


In [49]:
# Dummy variable trap -> 3 variable only needs 2 cols

# list to array
X = np.asarray(X)

X = X[:, 1:]
print(X[:5])

[[0.0000000e+00 0.0000000e+00 6.1900000e+02 0.0000000e+00 4.2000000e+01
  2.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00
  1.0134888e+05]
 [0.0000000e+00 1.0000000e+00 6.0800000e+02 0.0000000e+00 4.1000000e+01
  1.0000000e+00 8.3807860e+04 1.0000000e+00 0.0000000e+00 1.0000000e+00
  1.1254258e+05]
 [0.0000000e+00 0.0000000e+00 5.0200000e+02 0.0000000e+00 4.2000000e+01
  8.0000000e+00 1.5966080e+05 3.0000000e+00 1.0000000e+00 0.0000000e+00
  1.1393157e+05]
 [0.0000000e+00 0.0000000e+00 6.9900000e+02 0.0000000e+00 3.9000000e+01
  1.0000000e+00 0.0000000e+00 2.0000000e+00 0.0000000e+00 0.0000000e+00
  9.3826630e+04]
 [0.0000000e+00 1.0000000e+00 8.5000000e+02 0.0000000e+00 4.3000000e+01
  2.0000000e+00 1.2551082e+05 1.0000000e+00 1.0000000e+00 1.0000000e+00
  7.9084100e+04]]


In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Part 2 - Now let's make the ANN!**

In [53]:
import keras

Using TensorFlow backend.


In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initializing the ANN

classifier = Sequential() # Defining the sequence of layers

In [59]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units= 6, activation = "relu", input_dim = 11))
# units -> output dimension, activation -> activation function


In [0]:
# Adding the second hidden layer
classifier.add(Dense(units= 6, activation = "relu")

In [0]:
# Adding the final layer
classifier.add(Dense(units= 1, activation = "sigmoid", input_dim = 6))

# If the output has more than 1 dimensions (2 or more outputs)
# Then units = 2 or more; activation = "softmax" (just like sigmoid but more outputs)

In [62]:
# Compiling the ANN
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# binary_crossentropy for 1 output model
# cross_entropy for more



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [63]:
# Fitting the ANN to the training set
classifier.fit(X_train, y_train, batch_size=10, epochs=100)




Epoch 1/100





8000/8000 [==============================] - 12s 2ms/step - loss: 0.5966 - acc: 0.6936
Epoch 2/100
8000/8000 [==============================] - 3s 344us/step - loss: 0.4443 - acc: 0.8059
Epoch 3/100
8000/8000 [==============================] - 3s 344us/step - loss: 0.4147 - acc: 0.8165
Epoch 4/100
8000/8000 [==============================] - 3s 343us/step - loss: 0.3979 - acc: 0.8252
Epoch 5/100
8000/8000 [==============================] - 3s 336us/step - loss: 0.3824 - acc: 0.8360
Epoch 6/100
8000/8000 [==============================] - 3s 341us/step - loss: 0.3678 - acc: 0.8456
Epoch 7/100
8000/8000 [==============================] - 3s 344us/step - loss: 0.3579 - acc: 0.8512
Epoch 8/100
8000/8000 [==============================] - 3s 337us/step - loss: 0.3533 - acc: 0.8540
Epoch 9/100
8000/8000 [==============================] - 3s 341us/step - loss: 0.3499 - acc: 0.8560
Epoch 10/100
8000/8000 [==============================] - 3s 337us/step - loss: 0.3479 - acc:

**Part 3 - Making the predictions and evaluating the model**

In [66]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred[:6]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True]])

In [0]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

In [68]:
cm

array([[1523,   72],
       [ 204,  201]])

In [70]:
accuracy = (cm[0][0]+cm[1][1])/2000
print(accuracy)

0.862
